### ISSUE TITLE
Texture::bind and Shader::bind are now static and need an argument

### ISSUE THREAD

**Issue by L-P** [bastienleonard/pysfml-cython#54]
pysfml is broken since https://github.com/LaurentGomila/SFML/commit/91e1743516377e16d675b6486301aeba5b20bef8

```
gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/usr/include/python3.2mu -c src/sfml.cpp -o build/temp.linux-x86_64-3.2/src/sfml.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
src/sfml.cpp: In function ‘PyObject* __pyx_pf_4sfml_7Texture_12bind(__pyx_obj_4sfml_Texture*, int)’:
src/sfml.cpp:27247:84: error: no matching function for call to ‘sf::Texture::bind(sf::Texture::CoordinateType)’
src/sfml.cpp:27247:84: note: candidate is:
In file included from /usr/local/include/SFML/Graphics/Font.hpp:33:0,
                 from /usr/local/include/SFML/Graphics.hpp:35,
                 from src/sfml.cpp:264:
/usr/local/include/SFML/Graphics/Texture.hpp:454:17: note: static void sf::Texture::bind(const sf::Texture*, sf::Texture::CoordinateType)
/usr/local/include/SFML/Graphics/Texture.hpp:454:17: note:   no known conversion for argument 1 from ‘sf::Texture::CoordinateType’ to ‘const sf::Texture*’
src/sfml.cpp: In function ‘PyObject* __pyx_pf_4sfml_6Shader_16bind(__pyx_obj_4sfml_Shader*)’:
src/sfml.cpp:39040:30: error: no matching function for call to ‘sf::Shader::bind()’
src/sfml.cpp:39040:30: note: candidate is:
In file included from /usr/local/include/SFML/Graphics.hpp:41:0,
                 from src/sfml.cpp:264:
/usr/local/include/SFML/Graphics/Shader.hpp:471:17: note: static void sf::Shader::bind(const sf::Shader*)
/usr/local/include/SFML/Graphics/Shader.hpp:471:17: note:   candidate expects 1 argument, 0 provided
src/sfml.cpp: At global scope:
src/sfml.cpp:34929:39: warning: ‘__pyx_obj_4sfml_Vertex* __pyx_f_4sfml_wrap_vertex_instance(sf::Vertex*)’ defined but not used [-Wunused-function]
error: command 'gcc' failed with exit status 1

```
